const TECHNOLOGY_ICON_ALIASES: Readonly<Record<string, string>> = {
  hsts: "HSTS.svg",
  "amazon cloudfront": "Amazon Cloudfront.svg",
  "google tag manager": "Google Tag Manager.svg",
  cloudflare: "CloudFlare.svg",
  "http/3": "HTTP3.svg",
  java: "Java.svg",
  "amazon s3": "Amazon S3.svg",
  "cloudflare bot management": "CloudFlare.svg",
  nginx: "Nginx.svg",
  webpack: "Webpack.svg",
  react: "React.svg",
  "adobe experience manager": "Adobe Experience Manager Franklin.svg",
  imperva: "Imperva.svg",
  azure: "Azure.svg",
  "microsoft asp.net": "Microsoft ASP.NET.svg",
  akamai: "Akamai.svg",
  "apache http server": "Apache.svg",
  php: "PHP.svg",
  "azure front door": "Azure.svg",
  envoy: "Envoy.svg",
  jquery: "jQuery.svg",
  "node.js": "Node.js.svg",
  mysql: "MySQL.svg",
  bootstrap: "Bootstrap.svg",
  express: "Express.svg",
  "google cloud": "Google Cloud.svg",
  "amazon elb": "Amazon ELB.svg",
  "google cloud cdn": "Google Cloud.svg",
  wordpress: "WordPress.svg",
  unpkg: "Unpkg.svg",
  "next.js": "Next.js.svg",
  basic: "Basic Authentication.svg",
  "wp rocket": "WP Rocket.svg",
  "azure edge network": "Azure.svg",
  kinsta: "Kinsta.svg",
  slick: "Slick.svg",
  stimulus: "Stimulus.svg",
  angularjs: "AngularJS.svg",
  "azure monitor": "Azure.svg",
  "underscore.js": "Underscore.js.svg",
  "yoast seo": "Yoast SEO.svg",
  trustarc: "https://github.com/trustarc.png?size=64",
  "materialize css": "https://github.com/materializecss.png?size=64",
  render: "Render.svg",
  sucuri: "https://github.com/Sucuri.png?size=64",
  "socket.io": "Socket.io.svg",
  readme: "ReadMe.svg",
  tealium: "https://github.com/Tealium.png?size=64",
  zipkin: "https://github.com/openzipkin.png?size=64",
  ketch: "https://github.com/ketch-com.png?size=64",
  "klarna checkout": "Klarna.svg",
  absorb: "Absorb.svg",
  frontpage: "Microsoft.svg",
  "authorize.net": "authorize.net.svg",
  accesso: "Accesso.svg",
  acuityads: "AcuityAds.svg",
  almalinux: "AlmaLinux.svg",
  aos: "AOS.svg",
  asciinema: "Asciinema.svg",
  astro: "Astro.svg",
  "atlassian jira": "Atlassian Jira.svg",
  axios: "Axios.svg",
  bamboohr: "BambooHR.svg",
  bentobox: "Bentobox.svg",
  blocksy: "Blocksy.svg",
  blogger: "Blogger.svg",
  bugzilla: "Bugzilla.svg",
  "campaign monitor": "Campaign Monitor.svg",
  "chart.js": "Chart.js.svg",
  "checkout.com": "Checkout.com.svg",
  complianz: "Complianz.svg",
  createjs: "CreateJS.svg",
  divi: "Divi.svg",
  docusaurus: "docusaurus.svg",
  "download monitor": "Download Monitor.svg",
  drupal: "Drupal.svg",
  dynamicweb: "Dynamicweb.svg",
  elementor: "Elementor.svg",
  extjs: "ExtJS.svg",
  "fat-free framework": "Fat-Free Framework.svg",
  fingerprintjs: "FingerprintJS.svg",
  "fitvids.js": "FitVids.JS.png",
  flexslider: "FlexSlider.png",
  gatsby: "Gatsby.svg",
  "jquery ui": "jQuery UI.svg",
  modernizr: "Modernizr.svg",
  okta: "Okta.svg",
  "redux framework": "Redux Framework.svg",
  sentry: "Sentry.svg",
  varnish: "Varnish.svg",

  // High-use detections not represented in the local Wappalyzer icon set.
  // GitHub avatar images keep these logos cacheable without bundling another
  // third-party icon package.
  iis: "Microsoft.svg",
  "microsoft httpapi": "Microsoft.svg",
  openssl: "https://github.com/openssl.png?size=64",
  "yoast seo premium": "Yoast SEO.svg",
  wpml: "https://github.com/OnTheGoSystems.png?size=64",
  popper: "https://github.com/floating-ui.png?size=64",
  "reveal.js": "https://github.com/hakimel.png?size=64",
  "site kit": "Google.svg",
  "salesforce desk": "https://github.com/salesforce.png?size=64",
  instana: "https://github.com/instana.png?size=64",
  "w3 total cache": "WordPress.svg",
  "phusion passenger": "https://github.com/phusion.png?size=64",
  tinymce: "https://github.com/tinymce.png?size=64",
  "wordpress super cache": "WordPress.svg",
  outsystems: "https://github.com/OutSystems.png?size=64",
  "gravity forms": "https://github.com/rocketgenius.png?size=64",
  "genesys cloud": "https://github.com/MyPureCloud.png?size=64",
  handlebars: "https://github.com/handlebars-lang.png?size=64",
  siteground: "https://github.com/siteground.png?size=64",
  hcaptcha: "https://github.com/hCaptcha.png?size=64",
  plyr: "https://github.com/sampotts.png?size=64",
  mootools: "https://github.com/mootools.png?size=64",
  "litespeed cache": "https://github.com/litespeedtech.png?size=64",
  "microsoft word": "Microsoft.svg",
  summernote: "https://github.com/summernote.png?size=64",
  sweetalert2: "https://github.com/sweetalert2.png?size=64",
  "slider revolution": "https://github.com/themepunch.png?size=64",
  "tippy.js": "https://github.com/atomiks.png?size=64",
  "vue.js": "vue.svg",
  "google pagespeed": "Google.svg",
  "application request routing": "Microsoft.svg",
  "yoast seo for shopify": "Yoast SEO.svg",
  igodigital: "https://github.com/salesforce.png?size=64",
  "acquia cloud platform": "acquia-cloud-platform.svg",
  "tiny slider": "https://github.com/ganlanyuan.png?size=64",
  "jquery modal": "jQuery.svg",
  openresty: "https://github.com/openresty.png?size=64",
  quicklink: "https://github.com/GoogleChromeLabs.png?size=64",
  passage: "https://github.com/passageidentity.png?size=64",
  "queue-it": "https://github.com/queueit.png?size=64",
  polyfill: "https://github.com/Financial-Times.png?size=64",
  moxie: "https://github.com/moxiecode.png?size=64",
  moodle: "https://github.com/moodle.png?size=64",
  nicepage: "https://github.com/nicepage.png?size=64",
  openlayers: "https://github.com/openlayers.png?size=64",
  nvd3: "https://github.com/novus.png?size=64",
  speedcurve: "https://github.com/speedcurve.png?size=64",
  sonarqubes: "https://github.com/SonarSource.png?size=64",
  suse: "https://github.com/SUSE.png?size=64",
  "vonage video api": "https://github.com/Vonage.png?size=64",
  tornadoserver: "https://github.com/tornadoweb.png?size=64",
  sharethis: "https://github.com/ShareThis.png?size=64",
  woocommerce: "https://github.com/woocommerce.png?size=64",
  recurly: "https://github.com/recurly.png?size=64",
  redoc: "https://github.com/Redocly.png?size=64",
  "script.aculo.us": "https://github.com/prototypejs.png?size=64",
  sap: "https://github.com/SAP.png?size=64",
  ghost: "https://github.com/TryGhost.png?size=64",
  geetest: "https://github.com/GeeTeam.png?size=64",
  "hello bar": "https://github.com/hellobar.png?size=64",
  hugo: "https://github.com/gohugoio.png?size=64",
  history: "https://github.com/browserstate.png?size=64",
  fullcalendar: "https://github.com/fullcalendar.png?size=64",
  "angular material": "Angular.svg",
  flickity: "https://github.com/metafizzy.png?size=64",
  "crypto-js": "https://github.com/brix.png?size=64",
  "math.js": "https://github.com/josdejong.png?size=64",
  "kadence wp kadence": "https://github.com/stellarwp.png?size=64",
  "microsoft sharepoint": "Microsoft.svg",
  mod_jk: "https://github.com/apache.png?size=64",
  mkdocs: "https://github.com/mkdocs.png?size=64",
  "jquery mobile": "jQuery.svg",
  jekyll: "https://github.com/jekyll.png?size=64",
  "javaserver pages": "Java.svg",
  jenkins: "https://github.com/jenkinsci.png?size=64",
  "jquery devbridge autocomplete": "https://github.com/devbridge.png?size=64",
  jetty: "https://github.com/jetty.png?size=64",
};

const VERSION_SUFFIX = /:(?:\d[\w.+-]*|unknown|none|next|[a-f\d]{7,})$/i;

export function resolveTechnologyIcon(name: string, detectedIcon: string): string {
  const icon = detectedIcon.trim();
  if (icon) return icon;

  const normalizedName = name.trim().toLowerCase().replace(VERSION_SUFFIX, "");
  const alias = TECHNOLOGY_ICON_ALIASES[normalizedName] ?? "";
  if (!alias || /^https?:\/\//i.test(alias) || alias.startsWith("/")) return alias;
  return `/icons/${alias}`;
}

export function resolveIconUrl(icon: string, baseUrl: string): string {
  if (!icon) return "";
  if (/^https?:\/\//i.test(icon) || icon.startsWith("/")) return icon;

  const base = baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`;
  return encodeURI(`${base}${icon}`);
}
